version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    working_directory: ~/poller
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install --no-dev
      - run: npm install
      - run: npm run prod
