version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: circleci
          MYSQL_PASSWORD: circleci
          MYSQL_DATABASE: poller
    working_directory: ~/poller
    steps:
      - checkout
      - run: sudo composer self-update
      - run: sudo docker-php-ext-install pdo_mysql
      - run: composer install --no-dev
      - run: npm install #@todo re-examine
      - run: npm install vue bootstrap-vue bootstrap
      - run: npm run prod
      - run: mv .env.circleci .env
      - run: php artisan migrate --force
      - run: php artisan db:seed --force

