version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    working_directory: ~/poller
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install --no-dev
      - run: npm install #@todo re-examine
      - run: npm install vue bootstrap-vue bootstrap
      - run: npm run prod
      - run: mv .env.circleci .env
  tests:
    build:
      docker:
        - imagine: circleci/mysql:latest
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD=true
            MYSQL_ROOT_HOST="%"
            MYSQL_USER=circleci
            MYSQL_DATABASE=poller
      working_directory: ~/poller
      steps:
        - run: php artisan migrate --force
        - run: php artisan db:seed --force
