version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.1-fpm-buster #https://github.com/phpdaily/php/blob/master/7.4-dev/buster/fpm/Dockerfile
    working_directory: ~/poller
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install --no-dev
      - run: npm run prod
